const ProjectGenerator = require("../projectGenerator");

const generator = new ProjectGenerator();

module.exports = {
    keywords: [
        "website",
        "web",
        "html",
        "css",
        "javascript",
        "js",
        "build",
        "create",
        "landing page",
        "portfolio",
        "restaurant",
        "school",
        "blog",
        "shop"
    ],

    run(message) {

        return generator.create(
            "Project",

`<!DOCTYPE html>
<html>
<head>
<title>Pendium Project</title>
<link rel="stylesheet" href="style.css">
</head>
<body>

<h1>${message}</h1>
<p>Generated by Pendium AI</p>

<script src="script.js"></script>

</body>
</html>`,

`body{
    background:#111;
    color:white;
    font-family:Arial;
    text-align:center;
    padding:50px;
}`,

`console.log("Generated by Pendium AI");`
        );

    }
};